[package]
name = "sql"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# sqlparser = "0.32.0"
sqlparser = { path="../sqlparser"}

serde = "~1.0.126"
serde_derive = "~1.0.126"
regex = "1.5.4"
